DROP TABLE IF EXISTS cubes;

CREATE TABLE cubes (
  id INTEGER PRIMARY KEY,
  state JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


DROP TABLE IF EXISTS moves;

CREATE TABLE moves (
  id SERIAL PRIMARY KEY,
  cube_id INTEGER NOT NULL REFERENCES cubes(id) ON DELETE CASCADE,
  face TEXT NOT NULL,
  direction TEXT NOT NULL,
  move_type TEXT NOT NULL DEFAULT 'manual',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);